version: '1.0'

services:
  fastapi_app:
    image: fastapi_app_image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    networks:
      - demo-network


networks:
  demo-network:
    external: true
